# Generated by Django 5.2 on 2025-06-28 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the department", max_length=255, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the department",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the department",
                        null=True,
                    ),
                ),
                (
                    "established_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the department was established",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("duration_years", models.IntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="api.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Speciality",
                "verbose_name_plural": "Specialties",
                "ordering": ["name"],
                "unique_together": {("department", "name")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "speciality",
                    models.ForeignKey(
                        help_text="The speciality the student is enrolled in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="api.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["last_name", "first_name"],
                "unique_together": {("first_name", "last_name", "date_of_birth")},
            },
        ),
    ]
