# Generated by Django 5.2 on 2025-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="studentid",
            field=models.CharField(
                default="stud",
                help_text="Unique identifier for the student, e.g., student ID",
                max_length=20,
                unique=True,
            ),
        ),
    ]
