# Generated by Django 5.2 on 2025-06-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_student_studentid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="studentid",
            new_name="student_id",
        ),
    ]
